name: Flutter Build Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run Build Runner Generation
      run: flutter pub run build_runner build --delete-conflicting-outputs

    - name: Build Android APK
      run: flutter build apk --release

    - name: Build iOS App (Unsigned)
      run: flutter build ios --no-codesign --release

    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Zip iOS App Bundle
      run: |
        cd build/ios/iphoneos
        zip -r ../../../ckd_nutrition_ios.zip Runner.app

    - name: Upload iOS App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: ios-release-app
        path: ckd_nutrition_ios.zip
